// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8OCdSFWiaIDxQU8XxgxQaxRBnEsam4kI',
    appId: '1:490049761282:web:ebbbe9675377130774f71b',
    messagingSenderId: '490049761282',
    projectId: 'agrilink-47f3f',
    authDomain: 'agrilink-47f3f.firebaseapp.com',
    storageBucket: 'agrilink-47f3f.firebasestorage.app',
    measurementId: 'G-482XWC4HDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMVMmoVnPkB9YlySa8g5m7l0nT8l0JBz4',
    appId: '1:490049761282:android:43995fef8fe50ef274f71b',
    messagingSenderId: '490049761282',
    projectId: 'agrilink-47f3f',
    storageBucket: 'agrilink-47f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqHYWBL14J2ciiK0t7f4ptJl33QAZ5CFM',
    appId: '1:490049761282:ios:dad795c242fc281f74f71b',
    messagingSenderId: '490049761282',
    projectId: 'agrilink-47f3f',
    storageBucket: 'agrilink-47f3f.firebasestorage.app',
    iosBundleId: 'com.example.agrilinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqHYWBL14J2ciiK0t7f4ptJl33QAZ5CFM',
    appId: '1:490049761282:ios:dad795c242fc281f74f71b',
    messagingSenderId: '490049761282',
    projectId: 'agrilink-47f3f',
    storageBucket: 'agrilink-47f3f.firebasestorage.app',
    iosBundleId: 'com.example.agrilinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8OCdSFWiaIDxQU8XxgxQaxRBnEsam4kI',
    appId: '1:490049761282:web:9624bf26bd906ac674f71b',
    messagingSenderId: '490049761282',
    projectId: 'agrilink-47f3f',
    authDomain: 'agrilink-47f3f.firebaseapp.com',
    storageBucket: 'agrilink-47f3f.firebasestorage.app',
    measurementId: 'G-V7FCDWH1D1',
  );
}
